# Generated by Django 4.2.16 on 2026-07-28 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(default='[]')),
                ('wage_amount', models.FloatField(default=45.0)),
                ('wage_basis', models.CharField(default='Hourly', max_length=50)),
                ('experience_years', models.IntegerField(default=1)),
                ('availability', models.CharField(default='Immediate', max_length=100)),
                ('rating', models.FloatField(default=5.0)),
                ('efficiency_rating', models.FloatField(default=90.0)),
                ('portfolio_url', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('sender_role', models.CharField(max_length=50)),
                ('receiver_id', models.IntegerField()),
                ('receiver_role', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
                ('profile_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PastWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('client_company', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project_efficiency', models.IntegerField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_work', to='api.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.FloatField()),
                ('required_skills', models.TextField(default='[]')),
                ('duration', models.CharField(max_length=100)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.recruiter')),
            ],
        ),
    ]
